package javabeat.net.springboot.domain;

public enum ActivityCategory {
	CINEMA, JOGGING, GYM, COFFEE, MUSEUM, THEATER, PAINTBALL, LASERDOME, PICKNICK, RESTAURANT, ESCAPEROOM,
	SKIING, SPA, ICESKATING, BOWLING, CLIMBING, BILLIARDS, SLEDGING, SHOPPING, WATERPARK
}
