package javabeat.net.springboot.domain;

public enum ActivityCategory {
	CINEMA, JOGGING, GYM, COFFEE, MUSEUM, THEATER, PAINTBALL, LASERTAG, PARK, RESTAURANT, ESCAPEROOM,
	SKIING, SPA, ICESKATING, BOWLING, CLIMBING, BILLIARDS, SLEDGING, SHOPPING, SWIMMING
}
